management:
    endpoints:
        web:
            cors:
                allowed-origins: http//localhost:3000
                allowed-methods: GET,POST, PUT, PATCH, DELETE

spring:
    servlet:
        csrf:
            enabled: false
